### ISSUE TITLE
[TODO] Add --api flag as the 4th option to ' Time to Start Cooking!'

### ISSUE THREAD

**Issue by miatrinity** [miatrinity/railsnew.io#22]
The best home for this is in the 'Time to Start Cooking!' section

Semantics - same as 'omakase' (ie everything 'on') plus --api flag.

**Comment by tibbon** [comment]
I'd move to re-open this one. The `--api` flag is pretty essential I think.

**Comment by miatrinity** [comment]
Huh, after being here alone for so long, it's so weird (but great) to receive an external comment 🥇 

Ok this has been re-opened and will be added with the next release!

**Comment by miatrinity** [comment]
This has been implemented and deployed yesterday:

![image](https://user-images.githubusercontent.com/59438283/83588651-241cf400-a552-11ea-9e92-89ebdb31a21f.png)
