### ISSUE TITLE
Result constantly returning `--template "undefined"`

### ISSUE THREAD

**Issue by fig** [miatrinity/railsnew.io#70]
Core Rails option flags working fine but no matter what extras are chosen, the resultant command always contains `--template "undefined"`

**Comment by miatrinity** [comment]
Ooops - just came back from vacation and saw this!

Moral of the story: never deploy to production before going on a longer trip ¯\_(ツ)_/¯.

Working on the fix now!

**Comment by miatrinity** [comment]
All set!
